### PR TITLE
Fix build on Xcode 15 and handle of values up to 256 in length

### PR DESCRIPTION
**Pull request by tkgstrator**
Fixed a problem that caused build error on above Xcode 15 due to the argument of the shell script containing files other than *.swift.

In addition, bacause the current version uses UUID as the encryption key, the secret value could only be specified up to the length of 32, and an index out of range would be occured. The fact that the length of the secret is limited to 32 characters may not be sufficient for application development. For example, Realm require a 64-character string as the encryption key.

Therefore, I made the encryption key longer so that it can handle up to 256 characters.

Sincerely.

### CODE REVIEW

**Comment by MasamiYamate** [comment]
Dear @tkgstrator

Hi,

Thank you for your pull request. I apologize that I haven't been able to maintain this project recently.
I really appreciate your fixes and suggestions.
I will take some time today to review the contents and behavior of the pull request.
Thank you again for your contribution.

Best regards,

**Comment by tkgstrator** [comment]
Thank you for your reply!

Nevertheless, it may be better to use AES block cipher mode of operation as it is not useful to make the key lengh be longer meaningless.

https://developer.apple.com/documentation/cryptokit/

**Comment by MasamiYamate** [comment]
For now, as a temporary measure, I will adopt the contents of the pull request.
Due to a heavy workload, it's challenging to find private development time. However, I would like to make the necessary adjustments adopting Cryptokit when the timing allows. 

Thank you for your suggestion.

**Review by MasamiYamate — APPROVED** [review]
LGTM

Thank you for the pull request.

**Pull request merged**
